---

name: Plumber Auto Merge
description: GitHub Action that merges PR if specified conditions are met

branding:
  icon: git-merge
  color: green

inputs:
  pr-metadata:
    required: true
    description: Pull Request metadata
  config-path:
    required: false
    default: .github/auto-merge.yml
    description: Path to configuration file

  tracker:
    required: false
    description: tracker ID
  tracker-type:
    required: false
    default: 'none'
    description: tracker type, supported values are 'bugzilla' and 'jira'

  bugzilla-instance:
    description: Bugzilla instance URL
    default: https://bugzilla.redhat.com
  bugzilla-api-token:
    description: Bugzilla API TOKEN

  jira-instance:
    description: Jira instance URL
    default: https://issues.redhat.com
  jira-api-token:
    description: Jira API TOKEN

  set-status:
    required: false
    default: 'false'
    description: Set check-run status on Pull Request
  status-title:
    required: false
    default: Auto Merge
    description: H3 title of status message

  token:
    required: true
    description: GitHub TOKEN or PAT

outputs:
  status:
    description: Status message of the validation

runs:
  using: node20
  main: dist/index.js
